---
title:  |
        | The Pitfalls of Bottom-Up Accountability: Evidence from Brazil
author: 
- "Danilo Freire[^freire]"
- "Manoel Galdino[^galdino]"
- "Umberto Mignozzetti[^mignozzetti]"
- "Jessica Voigt[^voigt]"
date: \today
thanks: "We thank Guilherme Fasolin, Stephen Herzog, and David Skarbek for their helpful comments. We are specially grateful to the staff of Transparência Brasil for their excellent research and technical assistance. Replication data and code are available at <http://github.com/umbertomignozzetti/tdp-accountability>."
abstract: "We study the effect of a mobile phone application designed to increase citizens' ability to monitor public works in Brazil. The app allowed individuals to find delayed school constructions in XXX Brazilian cities and send anonymous messages to politicians requestions information about construction delays and expected completion times. Our results show that the app has a null impact on the completion times subsequently reported by the municipalities. Additionally, we find that few politicians reacted to citizens' requests. These findings suggest it is difficult to motivate bottom-up accountability in new democracies, especially when politicians are unresponsive to non-electoral pressures. This paper has implications for the design of bottom-up accountability mechanisms."
abstractspacing: double
keywords: accountability, Brazil, field experiment, impact evaluation, state capacity, technology
fontsize: 12pt
margin: 2cm
urlcolor: darkblue
linkcolor: Mahogany
citecolor: Mahogany
spacing: double
papersize: a4paper
bibliography: references.bib
biblio-style: apalike
output:
  pdf_document:
    citation_package: natbib
    fig_caption: yes
    number_sections: yes
    keep_tex: no
    toc: no
    toc_depth: 3
    template: article-template.latex
---

```{r, message=FALSE, warning=FALSE, echo=FALSE}
# If you need to install any package while knitting the document
r <- getOption("repos")
r["CRAN"] <- "https://cran.rstudio.com/"
options(repos = r)
```

[^freire]: Postdoctoral Research Associate, The Political Theory Project, Brown University, Providence, RI 02912, USA, <danilofreire@brown.edu>, <http://danilofreire.github.io>.

[^galdino]: Executive Diretor, Transparência Brazil, São Paulo, SP, Brazil, [mcz.fea@gmail.com](mailto:mcz.fea@gmail.com), <https://www.transparencia.org.br>.

[^mignozzetti]: School of International Relations, Fundação Getulio Vargas, São Paulo, SP, Brazil and Wilf Family Department of Politics, NYU, NY, USA, [umberto.mig@nyu.edu](mailto:umberto.mig@nyu.edu), <http://umbertomig.com>. Corresponding author.

[^voigt]: Data Scientist, Transparência Brasil, São Paulo, SP, Brazil, [voigt.jessica@gmail.com](mailto:voigt.jessica@gmail.com), <https://www.linkedin.com/in/voigtjessica>.

\newpage

# Introduction\label{sec:intro}

One of the key determinants of efficient public service provision is a robust accountability system \citep{besley2003incentives,cameron2004public,o1998horizontal}. In its standard definition, accountability is the process of holding authorities into account for their actions \citep{finer1941administrative,mulgan2000accountability,o1990bureaucratic}. Recent studies show that accountability ensures that politicians act on behalf of voters \citep{freire2010ngp, moncrieffe1998reconceptualizing}, reduces the opportunities for rent-seeking and corruption \citep{deininger2005does,wenar2006accountability} and increases the efficiency of the public sector \citep{adsera2003you,bjorkman2009power}. Moreover, greater accountability is associated with higher levels of economic growth, not only because it limits state discretion in the economy, but also because it promotes social cohesion and long-term investments in human capital \citep{benhabib2010economic, cox2018executive, suebvises2018social,ponzetto2018social}.

However, accountability systems can take many forms. One promising model for democratic oversight is _bottom-up accountability_, in which citizens receive information about the shortcomings of a given project to help them monitor and pressure underperforming public officials \citep{kosack2014does, molina2016community,raffler2018weakness}. Proponents suggest bottom-up is an effective method of accountability because 1) constituents have first-hand information about the outcomes of local policies; 2) citizens have incentives to avoid corruption that directly affects them; 3) policy-makers are particularly sensitive to social punishment from their own communities \citep[570]{serra2011combining}. In a nutshell, bottom-up accountability offers a potential solution to the principal-agent dilemma in public service by aligning the interests of politicians and bureaucrats with those of the constituency they serve \citep[2]{raffler2018weakness}.

Here we assess the impact of a technology-driven solution that lowers the costs of evaluating public works and punishing political representatives in Brazil. The _Tá de Pé_ (TDP) mobile phone application allows Brazilian citizens to go to school construction sites, check their status, and request information to public authorities. TDP users can also take pictures from delayed works and submit them to a group of trained engineers, who then evaluate the execution of the project. If the engineers classify the construction as delayed, TDP sends a message to the mayor's office asking for completion estimates and explanations about why the building is unfinished. TDP received the 2016 Google Social Impact grant, earning more than 200 thousand popular votes, and it has been online since April 2017 in 1030 Brazilian municipalities.

Contrary to our expectations, the TDP app has delivered mixed results. Two findings are positive and in line with our theoretical predictions. From August 2017 to February 2019, TDP increased the likelihood of school completion by 6.8 percent (SE = X.X, t-test = XXX). Additionally, we find that pressure over the bureaucracy increased the investments in the schools by 157.5 percent (SE = X.XX, t-test = XXX). In contrast, our results show the app had a null impact on school constructions statistics. Brazilian politicians did not respond to the citizen's requests placed via the application. Therefore, our findings raise questions about the ability of citizens to hold representatives accountable using bottom-up strategies.     

# The _Tá de Pé_ App

# Methods

## Estimation

Our regression model is specified as follows:

$$Y_{i} = \alpha + \beta T_{i} + \gamma X_{i} + \theta Z_i + \epsilon_{i} $$

Where $i$ indexes the case. $Y_i$ in one the outcomes we described in the previous subsection. The $\beta$ coefficient is the quantity of interest (Average Treatment Effect). $T_i$ is a binary treatment indicator in which zero denotes that $i$ is in the control group, while 1 indicates that $i$ received the treatment. $\gamma$ is a vector of fixed effects and $X_i$ is a matrix of 27 Brazilian states' fixed effects. $\theta$ is a vector of additional controls and $Z_i$ is an array of control variables for the case $i$. Lastly, $\epsilon_i$ is the error term.

We cluster the standard errors at the municipal level, as the investment decisions are taken by the mayor’s offices.
As robustness, we fit two extra models. First, we re-run the main model where we have the following: (i) we ran a model without controls or fixed effects; (ii) we run the models adding the control variables, which are the same as the ones used in the covariate balance tests; (iii) we run the regression model with State fixed effects. The results are in the Appendix.
Second, we run the main models using inverse probability weights where we used block randomization and a one-to-one nearest neighborhood matching. We use the control variables as matching characteristics. These robustness checks are intended to correct the imbalance caused by the minimal control group approach that we employed in all three interventions.

# Results

# Discussion

# Conclusion



\newpage
\setlength{\parindent}{0cm}
\setlength{\parskip}{5pt}
